export type Person = {
  id: string;
  name: string;
  jobTitle: string;
  status: "active" | "offline" | "away";
  email: string;
  phone: string;
  tags: string[];
  address: string;
  avatar: string;
};

export const mockPeople: Person[] = [
  {
    id: "1",
    name: "Sarah",
    jobTitle: "Marketing Director",
    status: "active",
    email: "sarah@brightwave.co",
    phone: "(415) 283-9921",
    tags: ["Marketing", "SaaS"],
    address: "Pine St, San Francisco, CA 94109",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=sarah",
  },
  {
    id: "2",
    name: "James",
    jobTitle: "Sales Manager",
    status: "offline",
    email: "james@gmail.com",
    phone: "(646) 555-7310",
    tags: ["Sales", "Enterprise"],
    address: "West 42nd St, New York, NY 10036",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=james",
  },
  {
    id: "3",
    name: "Priya",
    jobTitle: "Product Manager",
    status: "active",
    email: "priya@auroratech.io",
    phone: "(312) 449-2278",
    tags: ["Product", "B2B"],
    address: "Madison St, Chicago, IL 60612",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=priya",
  },
  {
    id: "4",
    name: "Lucas",
    jobTitle: "Account Executive",
    status: "offline",
    email: "lucas@yahoo.com",
    phone: "(512) 930-4456",
    tags: ["Sales", "Startup"],
    address: "Austin, TX 78701",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=lucas",
  },
  {
    id: "5",
    name: "Emily",
    jobTitle: "Customer Success Lead",
    status: "active",
    email: "emily@zencloud.com",
    phone: "(206) 902-1884",
    tags: ["Customer Success"],
    address: "Seattle, WA 98101",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=emily",
  },
  {
    id: "6",
    name: "Michael",
    jobTitle: "HR Coordinator",
    status: "active",
    email: "michael@outlook.com",
    phone: "(617) 348-9922",
    tags: ["Technology", "SaaS"],
    address: "Massachusetts Ave, Cambridge, MA",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=michael",
  },
  {
    id: "7",
    name: "Daniel Carter",
    jobTitle: "CEO",
    status: "away",
    email: "daniel.carter@hrworks.io",
    phone: "(305) 776-5402",
    tags: ["HR", "Operations"],
    address: "3250 SW 3rd Ave, Miami, FL 33129",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=daniel",
  },
  {
    id: "8",
    name: "Robert Johnson",
    jobTitle: "Customer Success Lead",
    status: "away",
    email: "robert.j@ventureline.com",
    phone: "(702) 901-3347",
    tags: ["Executive", "Strategy"],
    address: "120 Las Vegas Blvd, Las Vegas, NV 89101",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=robert",
  },
  {
    id: "9",
    name: "Sophie Martin",
    jobTitle: "Design Lead",
    status: "active",
    email: "sophie.martin@designco.com",
    phone: "(503) 234-5678",
    tags: ["Design", "UI/UX"],
    address: "Portland, OR 97201",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=sophie",
  },
  {
    id: "10",
    name: "Alex Chen",
    jobTitle: "Software Engineer",
    status: "active",
    email: "alex.chen@techcorp.io",
    phone: "(408) 555-1234",
    tags: ["Engineering", "Frontend"],
    address: "San Jose, CA 95110",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=alex",
  },
  {
    id: "11",
    name: "Maria Garcia",
    jobTitle: "Data Analyst",
    status: "offline",
    email: "maria.garcia@dataanalytics.com",
    phone: "(214) 555-9876",
    tags: ["Analytics", "Data"],
    address: "Dallas, TX 75201",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=maria",
  },
  {
    id: "12",
    name: "David Kim",
    jobTitle: "Operations Manager",
    status: "active",
    email: "david.kim@operations.io",
    phone: "(303) 555-4567",
    tags: ["Operations", "Management"],
    address: "Denver, CO 80202",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=david",
  },
  {
    id: "13",
    name: "Lisa Anderson",
    jobTitle: "Content Writer",
    status: "away",
    email: "lisa.anderson@contentstudio.com",
    phone: "(404) 555-7890",
    tags: ["Content", "Writing"],
    address: "Atlanta, GA 30309",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=lisa",
  },
  {
    id: "14",
    name: "Tom Wilson",
    jobTitle: "DevOps Engineer",
    status: "active",
    email: "tom.wilson@devops.io",
    phone: "(206) 555-3456",
    tags: ["DevOps", "Infrastructure"],
    address: "Seattle, WA 98102",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=tom",
  },
  {
    id: "15",
    name: "Emma Brown",
    jobTitle: "Finance Manager",
    status: "offline",
    email: "emma.brown@financecorp.com",
    phone: "(617) 555-2345",
    tags: ["Finance", "Accounting"],
    address: "Boston, MA 02108",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=emma",
  },
  {
    id: "16",
    name: "Ryan Taylor",
    jobTitle: "QA Engineer",
    status: "active",
    email: "ryan.taylor@qa.io",
    phone: "(415) 555-6789",
    tags: ["QA", "Testing"],
    address: "San Francisco, CA 94102",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=ryan",
  },
  {
    id: "17",
    name: "Olivia Martinez",
    jobTitle: "Business Analyst",
    status: "active",
    email: "olivia.martinez@business.io",
    phone: "(312) 555-0123",
    tags: ["Business", "Analysis"],
    address: "Chicago, IL 60601",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=olivia",
  },
  {
    id: "18",
    name: "Noah White",
    jobTitle: "Security Specialist",
    status: "away",
    email: "noah.white@security.io",
    phone: "(202) 555-4567",
    tags: ["Security", "Cybersecurity"],
    address: "Washington, DC 20001",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=noah",
  },
  {
    id: "19",
    name: "Isabella Lee",
    jobTitle: "Product Designer",
    status: "active",
    email: "isabella.lee@productdesign.com",
    phone: "(213) 555-8901",
    tags: ["Design", "Product"],
    address: "Los Angeles, CA 90012",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=isabella",
  },
  {
    id: "20",
    name: "William Davis",
    jobTitle: "Technical Lead",
    status: "active",
    email: "william.davis@techlead.io",
    phone: "(512) 555-5678",
    tags: ["Engineering", "Leadership"],
    address: "Austin, TX 78702",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=william",
  },
];

